image: python:2.7

stages:
  - build_test
  - build
  - test

build_test:
  stage: build_test
  script:
    - apt-get update
    ## Configuring graphical interface
    - apt-get install -yqq xvfb
    - Xvfb :99 -screen 0 1280x720x24 -ac &
    - export DISPLAY=:99
    ## Downloading requirements
    - apt-get -y install openjdk-11-jre
    - apt-get -y install python-pip
    - apt-get -y install python-tk
    - apt-get -y install python-pytest
    ## Installing
    - ./install.sh
    ## Testing
    - pytest --ignore=Tests/test_Search.py
    - cd Tests
    - pytest test_Search.py::SearchOracleFunctionTestCase

build:
  stage: build
  script:
    - apt-get update
    ## Downloading requirements
    - apt-get -y install python-pip
    ## Building
    - python setup2.py bdist_wheel --universal
    - python setup2.py bdist_egg
  artifacts:
    when: on_success
    paths:
      - dist/*whl
      - dist/*egg

test:
  stage: test
  image: python:3.5
  dependencies:
    - build
  script:
    - apt-get update
    ## Configuring graphical interface
    - apt-get install -yqq xvfb
    - Xvfb :99 -screen 0 1280x720x24 -ac &
    - export DISPLAY=:99
    ## Downloading requirements
    - apt-get -y install openjdk-11-jre
    - apt-get -y install python-pip
    - apt-get -y install python-tk
    - apt-get -y install python-pytest
    ## Configuring tests
    - pip install coverage
    - pip install pytest
    - pip install pytest-timeout
    - cd dist/
    - pip install *.whl --user
    - cd ../Tests
    - ./coverage_all.sh